version: "3.9"

services:
  hz:
    image: hz-exp
    ports:
      - "8080-8081:8080"
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip

networks:
  overlay: